# 00 · Preflight — worked solutions

These are complete, explained solutions to the ten exercises in
`00_preflight.ipynb`. Try each exercise first. A different variable name or a
different sequence of correct steps is equally valid.

In [1]:
import matplotlib.pyplot as plt
import numpy as np

## 1. Variables and units

Store each fact separately so it can be reused in later calculations. An
f-string combines the values into readable output while keeping the units
visible.

In [2]:
sample_name = "granite"
depth_km = 6.4
density_kg_m3 = 2710
message = f"The {sample_name} sample came from {depth_km} km depth. "
message += f"Its density is {density_kg_m3} kg/m³."
print(message)

The granite sample came from 6.4 km depth. Its density is 2710 kg/m³.


## 2. Lists and slices

Python counts from zero. The stop in a slice is excluded, so `[:2]` selects
positions 0 and 1. A negative start counts from the end.

In [3]:
temperatures_c = [12.5, 14.0, 17.2, 15.8, 13.1]
print(temperatures_c[:2])
print(temperatures_c[-2:])
print(temperatures_c[2])

[12.5, 14.0]
[15.8, 13.1]
17.2


## 3. A condition

Check the highest threshold first. If `magnitude >= 6` is false, the next branch
checks whether the value is at least 4. Anything remaining must be below 4.

In [4]:
magnitude = 5.3
if magnitude >= 6:
    category = "large"
elif magnitude >= 4:
    category = "moderate"
else:
    category = "small"
print(category)

moderate


## 4. A loop and a function

One millimeter is one thousandth of a meter. The function expresses that rule
once, and the loop supplies each measurement in turn.

In [5]:
def millimeters_to_meters(distance_mm):
    return distance_mm / 1000

In [6]:
for distance_mm in [2, 5, 12]:
    print(millimeters_to_meters(distance_mm))

0.002
0.005
0.012


## 5. Array selection

NumPy calculates the mean over all five values. The comparison produces a
Boolean array, which is then used to retain only entries greater than 3.

In [7]:
measurements = np.array([1.2, 4.8, 3.1, 7.5, 2.0])
print(np.mean(measurements))
print(measurements[measurements > 3])

3.72
[4.8 3.1 7.5]


## 6. Vectorization and broadcasting

Adding `np.newaxis` turns the three slopes into a `(3, 1)` column. The six x
positions then broadcast across each row, giving one row per slope.

In [8]:
slopes = np.array([1.0, 2.0, 4.0])[:, np.newaxis]
x_values = np.arange(6.0)
lines = slopes * x_values + 0.5
print(lines, lines.shape)

[[ 0.5  1.5  2.5  3.5  4.5  5.5]
 [ 0.5  2.5  4.5  6.5  8.5 10.5]
 [ 0.5  4.5  8.5 12.5 16.5 20.5]] (3, 6)


## 7. Plotting

Row 1 is the second line and therefore has slope 2. Both axes identify a
quantity and a unit; the title identifies which line is shown.

In [9]:
fig, ax = plt.subplots(figsize=(5, 3))
ax.plot(x_values, lines[1])
ax.set(xlabel="Distance (km)", ylabel="Value (m)",
       title="Line with slope 2 m/km");

## 8. Matrix multiplication

The matrix has three rows, so it produces three predictions. Its two columns
combine with the two model values. The output shape `(3,)` therefore means one
predicted number for each row.

In [10]:
design = np.array([[1.0, 0.0], [1.0, 1.0], [1.0, 2.0]])
parameters = np.array([3.0, 0.4])
predictions = design @ parameters
print(predictions, predictions.shape)

[3.  3.4 3.8] (3,)


## 9. A linear solve

`solve` finds the two unknown values. Multiplying the matrix by that solution
should reproduce `b`; `np.allclose` confirms equality within floating-point
roundoff.

In [11]:
coefficients = np.array([[3.0, 1.0], [1.0, 2.0]])
outcomes = np.array([9.0, 8.0])
solution = np.linalg.solve(coefficients, outcomes)
print(solution, coefficients @ solution)
assert np.allclose(coefficients @ solution, outcomes)

[2. 3.] [9. 8.]


## 10. Least squares

The first column of ones represents the line's intercept, and the second column
contains x. The four observations do not lie on one exact line, so the residuals
are small rather than all zero.

In [12]:
x_values = np.array([0.0, 1.0, 2.0, 3.0])
data = np.array([1.0, 2.2, 2.9, 4.1])
design = np.column_stack([np.ones(x_values.size), x_values])
parameters, *_ = np.linalg.lstsq(design, data, rcond=None)

In [13]:
predictions = design @ parameters
differences = data - predictions
print("intercept and slope:", parameters)
print("predictions:", predictions)
print("differences:", differences)

intercept and slope: [1.05 1.  ]
predictions: [1.05 2.05 3.05 4.05]
differences: [-0.05  0.15 -0.15  0.05]


## Closing interpretation

These exercises use small values so every step can be inspected. The same
operations scale to longer scientific arrays: name quantities and units clearly,
inspect shapes, and verify a solution by using it to reproduce the data or
equation it was intended to explain.